const { onObjectFinalized } = require('firebase-functions/v2/storage');
const { onCall, HttpsError } = require('firebase-functions/v2/https');
const { initializeApp } = require('firebase-admin/app');
const { getFirestore, FieldValue } = require('firebase-admin/firestore');
const { getStorage } = require('firebase-admin/storage');
const { GoogleAuth } = require('google-auth-library');
const XLSX = require('xlsx');
const { parse } = require('csv-parse/sync');

initializeApp();
const db = getFirestore();
const googleAuth = new GoogleAuth({scopes:['https://www.googleapis.com/auth/spreadsheets.readonly']});

const STANDARD_TYPES = ['OVERVIEW','SAFETY','CDF','DSB','PSB','DVIC'];
const LOG_SHEET_ID = '1Hh-SaxsOQaBRadK7M1k-FWehlbi_s5CvZDAsluSF4ZU';
const REQUIRED = {
  OVERVIEW: [['delivery associate'],['overall score'],['packages delivered']],
  SAFETY: [['delivery associate','driver','transporter name','transporter_name','transporter id','transporterid','transporter_id'],['date station local time','date (station local time)','date'],['metric type']],
  CDF: [['delivery associate','driver','transporter id','transporterid','transporter_id'],['delivery date','date'],['feedback details']],
  DSB: [['delivery associate','driver','transporter id','transporterid','transporter_id'],['impacts scorecard']],
  PSB: [['delivery associate','driver','transporter id','transporterid','transporter_id'],['impacts scorecard'],['early arrivals','late arrivals','geo location','not attempted','contact compliance','out of return label','picked up, not returned']],
  DVIC: [['transporter name','transporter_name','delivery associate','driver','transporter id','transporterid','transporter_id'],['start date','start_date','date'],['duration']]
};

exports.processWeeklyUpload = onObjectFinalized({region:'us-east1'}, async (event) => { const name=event.data?.name||''; if(name.startsWith('staging/')) return; });
exports.deleteUpload = onCall({region:'us-east1'}, async (request) => {
  if(!request.auth) throw new HttpsError('unauthenticated','Acceso no preparado. Recarga la app.');
  const week=String(request.data?.week||'').trim(),station=String(request.data?.station||'').toUpperCase(),type=String(request.data?.type||'').toUpperCase();
  if(!/^\d{4}-W\d{2}$/.test(week)||!STANDARD_TYPES.includes(type)||!['DJX3','DJX4'].includes(station)) throw new HttpsError('invalid-argument','Documento inválido.');
  const id=`${week}_${station}_${type}`,ref=db.collection('uploads').doc(id),snap=await ref.get();
  if(snap.exists){const data=snap.data()||{};if(data.storagePath){try{await getStorage().bucket().file(data.storagePath).delete();}catch(err){if(err.code!==404)console.warn(err);}}}
  await deleteRecords(week,station,type);await ref.delete();await db.collection('generations').doc(week).set({status:'draft',updatedAt:FieldValue.serverTimestamp()},{merge:true});return{ok:true};
});

exports.generateWeek = onCall({region:'us-east1',timeoutSeconds:540,memory:'1GiB'},async(request)=>{
  if(!request.auth)throw new HttpsError('unauthenticated','Acceso no preparado. Recarga la app.');const week=String(request.data?.week||'').trim();if(!/^\d{4}-W\d{2}$/.test(week))throw new HttpsError('invalid-argument','Semana inválida.');
  const snap=await db.collection('uploads').where('week','==',week).get(),uploads=snap.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.storagePath&&STANDARD_TYPES.includes(x.type));if(!uploads.length)throw new HttpsError('failed-precondition',`No hay documentos cargados para ${week}.`);
  await db.collection('generations').doc(week).set({week,status:'processing',startedAt:FieldValue.serverTimestamp(),documentCount:uploads.length,error:''},{merge:true});
  const prepared=[],errors=[];for(const u of uploads){try{const[buffer]=await getStorage().bucket().file(u.storagePath).download(),rows=parseFile(buffer,u.fileName||u.storagePath.split('/').pop());if(rows.length<2)throw new Error('El archivo no contiene datos suficientes.');const validation=validate(rows[0],u.type);if(!validation.ok)throw new Error(validation.message);prepared.push({upload:u,records:normalize(rows,{week,station:u.station,type:u.type,fileName:u.fileName})});}catch(err){errors.push(`${u.station} ${u.type}: ${err.message||String(err)}`);await db.collection('uploads').doc(u.id).set({status:'error',error:String(err.message||err),updatedAt:FieldValue.serverTimestamp()},{merge:true});}}
  let logRecords=[],logSheetName='';if(!errors.length){try{const driverMap=buildDriverStationMap(prepared),infra=await fetchLogSheet('INFRA_LOG'),rescueResult=await fetchFirstLogSheet(['RESCUE_LOG','RESCUES_LOG']);logSheetName=rescueResult.sheetName;logRecords=parseLogRows({infra,rescues:rescueResult.rows},{week,fileName:`LOG · Google Sheets · ${logSheetName}`},driverMap);}catch(err){errors.push(`LOG automático: ${err.message||String(err)}`);}}
  if(errors.length){await db.collection('generations').doc(week).set({status:'error',error:errors.join(' | '),updatedAt:FieldValue.serverTimestamp()},{merge:true});throw new HttpsError('failed-precondition',`No se generó ${week}. ${errors.join(' | ')}`);}
  let totalRecords=0;for(const p of prepared){await replaceRecords(week,p.upload.station,p.upload.type,p.records);totalRecords+=p.records.length;await db.collection('uploads').doc(p.upload.id).set({status:'generated',rows:p.records.length,validation:'OK',error:'',generatedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()},{merge:true});}
  await deleteRecords(week,'DJX3','LOG');await deleteRecords(week,'DJX4','LOG');await writeRecords(logRecords.filter(r=>r.station==='DJX3'));await writeRecords(logRecords.filter(r=>r.station==='DJX4'));totalRecords+=logRecords.length;
  const driverCounts={};for(const station of ['DJX3','DJX4']){const q=await db.collection('records').where('week','==',week).where('station','==',station).where('sourceType','==','OVERVIEW').get();driverCounts[station]=q.size;}const logInfraCount=logRecords.filter(r=>r.kind==='LOG_INFRA').length,logRescueCount=logRecords.filter(r=>r.kind==='RESCUE').length;
  await db.collection('generations').doc(week).set({week,status:'generated',documentCount:prepared.length,records:totalRecords,driverCounts,logSource:'Google Sheets',logRescueSheet:logSheetName,logRecords:logRecords.length,logInfraCount,logRescueCount,error:'',generatedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()},{merge:true});return{week,documents:prepared.length,records:totalRecords,driverCounts,logRecords:logRecords.length,logInfraCount,logRescueCount,logRescueSheet:logSheetName};
});

async function fetchLogSheet(sheetName){const client=await googleAuth.getClient(),headers=await client.getRequestHeaders(),range=encodeURIComponent(`${sheetName}!A:Z`),url=`https://sheets.googleapis.com/v4/spreadsheets/${LOG_SHEET_ID}/values/${range}?majorDimension=ROWS&valueRenderOption=UNFORMATTED_VALUE`,res=await fetch(url,{headers});if(!res.ok){const body=await res.text();throw new Error(`No pude leer ${sheetName} desde Google Sheets (${res.status}). ${body.slice(0,180)}`);}const data=await res.json(),rows=Array.isArray(data.values)?data.values:[];if(!rows.length)throw new Error(`${sheetName} está vacío.`);const hc=rows[0].map(clean);if(!hc.includes('date')||!hc.includes('driver'))throw new Error(`${sheetName} no tiene las columnas Date y Driver.`);return rows;}
async function fetchFirstLogSheet(names){let lastErr=null;for(const name of names){try{return{sheetName:name,rows:await fetchLogSheet(name)}}catch(err){lastErr=err;}}throw lastErr||new Error('No encontré la hoja de rescates en LOG.');}
function parseFile(buffer,fileName){if(/\.csv$/i.test(fileName))return parse(buffer.toString('utf8'),{skip_empty_lines:true,relax_column_count:true});if(/\.xlsx?$/i.test(fileName)){const wb=XLSX.read(buffer,{type:'buffer',cellDates:true});return XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,defval:'',raw:false});}throw new Error('Formato no soportado. Usa CSV, XLS o XLSX.');}
function clean(v){return String(v??'').trim().toLowerCase().replace(/\s+/g,' ');}function idxMap(headers){const out={};headers.forEach((h,i)=>{const k=clean(h);if(k&&out[k]===undefined)out[k]=i;});return out;}function get(row,idx,names){for(const n of names){const i=idx[clean(n)];if(i!==undefined&&row[i]!==''&&row[i]!=null)return row[i];}return '';}function validate(headers,type){const normalized=headers.map(clean),missing=[];for(const alternatives of REQUIRED[type]||[]){if(!alternatives.some(x=>normalized.includes(clean(x))))missing.push(alternatives[0]);}return missing.length?{ok:false,message:`Archivo incorrecto para ${type}. Faltan columnas: ${missing.join(', ')}`}:{ok:true};}function truthy(v){const s=clean(v);return v===1||s==='1'||s==='y'||s==='yes'||s==='true'||s==='x';}function num(v){const n=Number(String(v??'').replace(/,/g,''));return Number.isFinite(n)?n:0;}function normalizeName(v){return clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();}function driverKey(name,transporterId){return String(transporterId||'').trim()||normalizeName(name).replace(/\s+/g,'_');}function base(meta,key,name,transporterId,kind,date,label,extra={}){return{week:meta.week,station:meta.station,sourceType:meta.type,fileName:meta.fileName,driverKey:key,driverName:String(name||''),transporterId:String(transporterId||''),kind,date:dateString(date),label:String(label||''),extra};}function dateString(v){const d=toDate(v);return d?d.toISOString().slice(0,10):String(v??'').trim();}
function normalize(rows,meta){const headers=rows[0],cleaned=headers.map(clean),idx=idxMap(headers),out=[];for(const row of rows.slice(1)){if(!row||row.every(v=>String(v??'').trim()===''))continue;if(meta.type==='OVERVIEW'){const name=String(get(row,idx,['delivery associate'])||'').trim(),packages=num(get(row,idx,['packages delivered']));if(!name||packages===0)continue;const transporterId=String(get(row,idx,['transporter id','transporterid','transporter_id'])||'').trim(),key=driverKey(name,transporterId);if(!key)continue;out.push(base(meta,key,name,transporterId,'OVERVIEW','','',{standing:get(row,idx,['overall standing']),overallScore:num(get(row,idx,['overall score'])),packages}));continue;}const name=get(row,idx,['delivery associate','driver','transporter name','transporter_name','name']),transporterId=get(row,idx,['transporter id','transporterid','transporter_id']),key=driverKey(name,transporterId);if(!key)continue;
if(meta.type==='SAFETY'){const date=get(row,idx,['date station local time','date (station local time)','date']),metric=String(row[7]??'').trim(),metricSubtype=String(row[8]??'').trim();if(clean(metric)==='high-g/bad mount')continue;if(metric)out.push(base(meta,key,name,transporterId,'INFRACTION',date,metric,{metricType:metric,metricSubtype}));}
else if(meta.type==='CDF'){const date=get(row,idx,['delivery date','date']),details=String(get(row,idx,['feedback details'])||'').trim(),skip=new Set(['week','delivery associate','driver','transporter id','transporterid','transporter_id','tracking id','delivery group id','feedback details','delivery date','date','station']),categories=[];cleaned.forEach((h,i)=>{if(h&&!skip.has(h)&&truthy(row[i]))categories.push(String(headers[i]||'').trim());});out.push(base(meta,key,name,transporterId,'COMPLAINT',date,categories.length?categories.join(' · '):(details||'Customer Delivery Feedback'),{details,categories}));}
else if(meta.type==='DSB'){if(!truthy(get(row,idx,['impacts scorecard'])))continue;const date=get(row,idx,['delivery date','date']),skip=new Set(['week','delivery associate','driver','transporter id','transporterid','tracking id','delivery group id','delivery date','impacts scorecard','station']);cleaned.forEach((h,i)=>{if(h&&!skip.has(h)&&truthy(row[i]))out.push(base(meta,key,name,transporterId,'DSB',date,headers[i]));});}
else if(meta.type==='PSB'){if(!truthy(get(row,idx,['impacts scorecard'])))continue;const date=get(row,idx,['pickup date','date']),categories=['early arrivals','late arrivals','geo location','not attempted','contact compliance','out of return label','picked up, not returned'];let found=0;for(const category of categories){const i=idx[clean(category)];if(i!==undefined&&truthy(row[i])){out.push(base(meta,key,name,transporterId,'FAILED_PICKUP',date,headers[i],{count:1}));found++;}}if(!found)out.push(base(meta,key,name,transporterId,'FAILED_PICKUP',date,'Failed Pickup',{count:1}));}
else if(meta.type==='DVIC'){const date=get(row,idx,['start date','start_date','date']),inspection=get(row,idx,['inspection type','inspection_type'])||'Pre-Trip',duration=num(get(row,idx,['duration']));out.push(base(meta,key,name,transporterId,'DVIC',date,inspection,{duration}));}}
return out;}
function buildDriverStationMap(prepared){const map=new Map();for(const p of prepared){if(p.upload.type!=='OVERVIEW')continue;for(const r of p.records){const n=normalizeName(r.driverName);if(n)map.set(n,{station:r.station,key:r.driverKey,transporterId:r.transporterId,name:r.driverName});}}return map;}
function parseLogRows({infra,rescues},meta,driverMap){const out=[];for(const [rows,kind] of [[infra,'LOG_INFRA'],[rescues,'RESCUE']]){const idx=idxMap(rows[0]);for(const row of rows.slice(1)){const name=String(get(row,idx,['driver'])||'').trim(),d=toDate(get(row,idx,['date']));if(!name||!d||weekKey(d)!==meta.week)continue;const mapped=driverMap.get(normalizeName(name));if(!mapped)continue;if(kind==='RESCUE'){out.push(base({week:meta.week,station:mapped.station,type:'LOG',fileName:meta.fileName},mapped.key,mapped.name,mapped.transporterId,'RESCUE',d,'Rescue',{stops:num(get(row,idx,['stop','stops'])),packages:num(get(row,idx,['packages'])),affects:String(get(row,idx,['affects'])||''),notes:String(get(row,idx,['notes'])||''),dispatcher:String(get(row,idx,['dispatcher'])||'')}));}else{const label=String(get(row,idx,['infraction','type','status','reason'])||'').trim();if(label)out.push(base({week:meta.week,station:mapped.station,type:'LOG',fileName:meta.fileName},mapped.key,mapped.name,mapped.transporterId,'LOG_INFRA',d,label,{}));}}}return out;}
function toDate(v){if(v instanceof Date&&!isNaN(v))return v;if(typeof v==='number'){if(v>20000&&v<80000)return new Date(Date.UTC(1899,11,30)+v*86400000);return null;}const s=String(v??'').trim();let m=s.match(/^(\d{4})[-\/]([01]?\d)[-\/]([0-3]?\d)/);if(m)return new Date(Date.UTC(+m[1],+m[2]-1,+m[3]));m=s.match(/^([0-3]?\d)[-\/]([01]?\d)[-\/](\d{4})/);if(m)return new Date(Date.UTC(+m[3],+m[2]-1,+m[1]));const d=new Date(s);return isNaN(d)?null:d;}function weekKey(date){const d=new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate())),day=d.getUTCDay(),sunday=new Date(d);sunday.setUTCDate(d.getUTCDate()-day);const year=sunday.getUTCFullYear(),first=new Date(Date.UTC(year,0,1)),firstSunday=new Date(first);firstSunday.setUTCDate(first.getUTCDate()+((7-first.getUTCDay())%7));const week=Math.floor((sunday-firstSunday)/604800000)+1;return`${year}-W${String(week).padStart(2,'0')}`;}
async function deleteRecords(week,station,sourceType){const q=await db.collection('records').where('week','==',week).where('station','==',station).where('sourceType','==',sourceType).get();for(let i=0;i<q.docs.length;i+=400){const batch=db.batch();q.docs.slice(i,i+400).forEach(d=>batch.delete(d.ref));await batch.commit();}}async function replaceRecords(week,station,sourceType,records){await deleteRecords(week,station,sourceType);await writeRecords(records);}async function writeRecords(records){for(let i=0;i<records.length;i+=400){const batch=db.batch();records.slice(i,i+400).forEach(r=>batch.set(db.collection('records').doc(),{...r,createdAt:FieldValue.serverTimestamp()}));await batch.commit();}}
